version: "3.8"

services:
    site:
        build: ./.docker/nginx
        container_name: nginx
        volumes:
            - "./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "./src:/var/www/html"
        ports:
            - "8000:80"
        environment:
            - NGINX_HOST=${NGINX_HOST}
        restart: always
        networks:
            - frontend

    php:
        build: ./.docker/php
        container_name: php
        env_file:
            - ".env"
        volumes:
            - "./.docker/php/config.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini"
            - "./src:/var/www/html"
        restart: always
        networks:
            - frontend
            - backend

    mysql:
        build: ./.docker/mysql
        container_name: mysql
        env_file:
            - ".env"
        command: --default-authentication-plugin=mysql_native_password
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        ports:
            - "3306:3306"
        volumes:
            - "./.docker/mysql/db:/var/lib/mysql"
        restart: always
        networks:
            - backend

networks:
    frontend:
        driver: bridge
    backend:
        driver: bridge